### ISSUE TITLE
nah

### ISSUE THREAD

**Issue by TKW905** [ecca/SourceMod-Plugins#1]

**Comment by Sarabveer** [comment]
+1 Fix it fix it fix it fix it fix it!!!

**Comment by JunkyBulgaria** [comment]
test this repository https://github.com/JunkyBulgaria/SourceMod-Plugins

**Comment by 404UserNotFound** [comment]
I actually fixed the plugin on my own as I noticed a glaring issue in the way the thing worked. I forget what the fix was.

EDIT: I remember. Whoever originally coded SourceSleuth fucked up and set "new time = length*60;" in "case 1" of the "SQL_CheckHim" function. Seems they copied the time integer from "case 3:" of the same function and forgot to remove the multiplication.

**Comment by JunkyBulgaria** [comment]
yeah, but there are more issues which i hopefully fixed so any feedback would be appreciated
